<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'Diaper Bag',
    'measure_unit' => 'piece',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 0,
    'id' => '1',
    'name' => 'Diaper Bag',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'Toy',
    'measure_unit' => 'piece',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '2',
    'name' => 'Toy',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'Wedding',
    'measure_unit' => 'piece',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => 'Wedding',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'Home & Beauty',
    'measure_unit' => 'piece',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => 'Home & Beauty',
  ),
);
?>